// Checks player ratings against the documented record: league MVPs, the major
// defensive and offensive awards, rookie-of-the-year seasons, the records a
// season is remembered for, and the Hall of Fame.
//
// The point is an independent yardstick. Ratings are editorial estimates, so
// left alone they drift toward whoever the author pictured most clearly. An
// award is not an opinion: a player either won it that season or did not. Where
// the two disagree, the rating is the thing that moved.
//
// A tier sets a floor, not a target — a rating above the floor is fine. `bust`
// is the one tier with a ceiling instead, for the high picks the pool carries
// as cautionary tales.
//
// TOLERANCE exists because these floors are a judgement, not a measurement: on
// a 40..99 editorial scale a two-point miss says nothing. Only a miss of three
// or more is reported, so the output stays a list of things worth looking at
// rather than a wall of rounding.
//
// Usage: node scripts/legacy-check.mjs [--all]
import { PLAYERS } from '../src/data/players.js';
import { overall, rawOverall } from '../src/engine/ratings.js';
import { POSITIONS } from '../src/data/positions.js';

// Floors by tier. A season can carry several tiers; the highest floor wins.
export const TOLERANCE = 3;

export const TIERS = {
  mvp:    { floor: 85, label: 'league MVP' },
  opoy:   { floor: 86, label: 'offensive player of the year' },
  dpoy:   { floor: 86, label: 'defensive player of the year' },
  record: { floor: 85, label: 'held a major record' },
  allpro: { floor: 84, label: 'first-team All-Pro that season' },
  hof:    { floor: 81, label: 'Hall of Fame' },
  roy:    { floor: 77, label: 'rookie of the year' },
  bust:   { ceiling: 68, label: 'a high pick who did not work out' },
};

// name + season -> tiers. Season-specific on purpose: a player's pool entry is
// one year of a career, and an award belongs to a year.
export const LEGACY = {
  // ---- quarterbacks ----
  'Sid Luckman|1943': ['mvp', 'hof'],
  'Sammy Baugh|1947': ['hof', 'record'],
  'Otto Graham|1953': ['mvp', 'hof'],
  'Bobby Layne|1952': ['hof', 'allpro'],
  'Johnny Unitas|1959': ['mvp', 'hof'],
  'Norm Van Brocklin|1960': ['mvp', 'hof'],
  'Milt Plum|1960': ['record'],
  'George Blanda|1961': ['record', 'hof'],
  'Y.A. Tittle|1963': ['mvp', 'hof'],
  'Len Dawson|1966': ['hof', 'allpro'],
  'Bart Starr|1966': ['mvp', 'hof'],
  'Daryle Lamonica|1967': ['mvp'],
  'Sonny Jurgensen|1967': ['hof', 'allpro'],
  'Joe Namath|1968': ['mvp', 'hof'],
  'Earl Morrall|1968': ['mvp'],
  'Roman Gabriel|1969': ['mvp'],
  'John Brodie|1970': ['mvp'],
  'Bob Griese|1971': ['hof', 'allpro'],
  'Roger Staubach|1971': ['hof', 'allpro'],
  'Ken Stabler|1974': ['mvp', 'hof'],
  'Fran Tarkenton|1975': ['mvp', 'hof'],
  'Bert Jones|1976': ['mvp'],
  'Terry Bradshaw|1978': ['mvp', 'hof'],
  'Brian Sipe|1980': ['mvp'],
  'Ken Anderson|1981': ['mvp'],
  'Dan Fouts|1981': ['hof', 'allpro'],
  'Joe Theismann|1983': ['mvp'],
  'Dan Marino|1984': ['mvp', 'hof', 'record'],
  'John Elway|1987': ['mvp', 'hof'],
  'Boomer Esiason|1988': ['mvp'],
  'Joe Montana|1989': ['mvp', 'hof'],
  'Warren Moon|1990': ['opoy', 'hof'],
  'Mark Rypien|1991': ['allpro'],
  'Troy Aikman|1993': ['hof', 'allpro'],
  'Steve Young|1994': ['mvp', 'hof'],
  'Brett Favre|1996': ['mvp', 'hof'],
  'Kurt Warner|1999': ['mvp', 'hof'],
  'Rich Gannon|2002': ['mvp'],
  'Peyton Manning|2004': ['mvp', 'hof', 'record'],
  'Ben Roethlisberger|2007': ['allpro'],
  'Drew Brees|2011': ['record', 'hof'],
  'Aaron Rodgers|2011': ['mvp'],
  'Tom Brady|2007': ['mvp', 'record'],
  'Tom Brady|2017': ['mvp'],
  'Matt Ryan|2016': ['mvp'],
  'Patrick Mahomes|2018': ['mvp'],
  'Lamar Jackson|2019': ['mvp'],
  'Justin Herbert|2021': ['allpro'],
  'C.J. Stroud|2023': ['roy'],
  'Jayden Daniels|2024': ['roy'],
  'Josh Allen|2024': ['mvp'],
  'Joe Burrow|2024': ['allpro'],
  'Ryan Leaf|1998': ['bust'],
  'JaMarcus Russell|2008': ['bust'],
  'Zach Wilson|2022': ['bust'],
  'Blaine Gabbert|2012': ['bust'],
  'Christian Ponder|2012': ['bust'],

  // ---- running backs ----
  'Bill Dudley|1946': ['mvp', 'hof'],
  'Steve Van Buren|1949': ['hof', 'allpro', 'record'],
  'Marion Motley|1950': ['hof', 'allpro'],
  'Doak Walker|1950': ['hof', 'allpro'],
  'Joe Perry|1954': ['hof', 'allpro'],
  'Hugh McElhenny|1954': ['hof'],
  'Frank Gifford|1956': ['mvp', 'hof'],
  'Rick Casares|1956': ['allpro'],
  'Lenny Moore|1958': ['hof', 'allpro'],
  'Paul Hornung|1960': ['hof', 'record'],
  'Jim Taylor|1962': ['mvp', 'hof'],
  'Cookie Gilchrist|1962': ['allpro'],
  'Jim Brown|1963': ['hof', 'record', 'allpro'],
  'Gale Sayers|1965': ['hof', 'roy', 'record'],
  'Leroy Kelly|1968': ['hof', 'allpro'],
  'Floyd Little|1969': ['hof'],
  'Larry Csonka|1972': ['hof', 'allpro'],
  'O.J. Simpson|1973': ['mvp', 'hof', 'record'],
  'Franco Harris|1975': ['hof', 'allpro'],
  'Chuck Foreman|1975': ['allpro'],
  'Walter Payton|1977': ['mvp', 'hof'],
  'Earl Campbell|1979': ['mvp', 'hof', 'roy'],
  'Billy Sims|1980': ['roy', 'allpro'],
  'Tony Dorsett|1981': ['hof', 'allpro'],
  'John Riggins|1983': ['hof', 'record'],
  'William Andrews|1983': ['allpro'],
  'Eric Dickerson|1984': ['hof', 'record', 'allpro'],
  'Marcus Allen|1985': ['mvp', 'hof'],
  'Herschel Walker|1988': ['allpro'],
  'Roger Craig|1988': ['allpro', 'record'],
  'Thurman Thomas|1991': ['mvp', 'hof'],
  'Barry Foster|1992': ['allpro'],
  'Emmitt Smith|1995': ['hof', 'record'],
  'Barry Sanders|1997': ['mvp', 'hof', 'record'],
  'Terrell Davis|1998': ['mvp', 'hof', 'record'],
  'Marshall Faulk|1999': ['opoy', 'hof'],
  'Edgerrin James|2000': ['hof', 'allpro'],
  'Priest Holmes|2002': ['allpro', 'record'],
  'Curtis Martin|2004': ['hof', 'allpro'],
  'Shaun Alexander|2005': ['mvp', 'record'],
  'LaDainian Tomlinson|2006': ['mvp', 'hof', 'record'],
  'Adrian Peterson|2012': ['mvp', 'hof'],
  'Jamaal Charles|2013': ['allpro'],
  'Todd Gurley|2017': ['opoy'],
  'Derrick Henry|2020': ['opoy', 'record'],
  'Jonathan Taylor|2021': ['allpro'],
  'Christian McCaffrey|2023': ['opoy'],
  'Saquon Barkley|2024': ['opoy', 'record'],
  'Ron Dayne|2000': ['bust'],
  'Trent Richardson|2012': ['bust'],

  // ---- receivers and tight ends ----
  'Don Hutson|1942': ['mvp', 'hof', 'record'],
  'Mac Speedie|1949': ['hof', 'allpro'],
  'Dante Lavelli|1949': ['hof'],
  'Tom Fears|1950': ['hof', 'record'],
  'Pete Pihos|1953': ['hof', 'allpro'],
  'Harlon Hill|1954': ['roy', 'allpro'],
  'Billy Howton|1956': ['allpro'],
  'Raymond Berry|1959': ['hof', 'allpro'],
  'Tommy McDonald|1961': ['hof', 'allpro'],
  'Del Shofner|1962': ['allpro'],
  'Bobby Mitchell|1962': ['hof', 'allpro'],
  'Art Powell|1963': ['allpro'],
  'Lance Alworth|1965': ['hof', 'allpro'],
  'Charley Taylor|1966': ['hof', 'allpro'],
  'Bob Hayes|1966': ['hof', 'allpro', 'record'],
  'Homer Jones|1967': ['record'],
  'Fred Biletnikoff|1969': ['hof'],
  'Paul Warfield|1971': ['hof', 'allpro'],
  'Harold Carmichael|1973': ['hof', 'allpro'],
  'Cliff Branch|1976': ['hof', 'allpro'],
  'Lynn Swann|1978': ['hof', 'allpro'],
  'John Stallworth|1979': ['hof'],
  'Charlie Joiner|1980': ['hof'],
  'John Jefferson|1980': ['allpro'],
  'James Lofton|1983': ['hof'],
  'Art Monk|1984': ['hof', 'record'],
  'Steve Largent|1985': ['hof', 'allpro'],
  'Jerry Rice|1995': ['hof', 'record', 'allpro'],
  'Cris Carter|1995': ['hof', 'record'],
  'Michael Irvin|1991': ['hof', 'allpro'],
  'Andre Reed|1991': ['hof'],
  'Sterling Sharpe|1992': ['allpro', 'record'],
  'Tim Brown|1997': ['hof', 'allpro'],
  'Terrell Owens|2001': ['hof', 'allpro'],
  'Marvin Harrison|2002': ['hof', 'record', 'allpro'],
  'Torry Holt|2003': ['allpro'],
  'Randy Moss|2007': ['hof', 'record', 'allpro'],
  'Larry Fitzgerald|2008': ['hof', 'allpro'],
  'Calvin Johnson|2012': ['hof', 'record', 'allpro'],
  'Antonio Brown|2015': ['allpro'],
  'Cooper Kupp|2021': ['opoy', 'record'],
  'Justin Jefferson|2022': ['opoy', 'allpro'],
  "Ja'Marr Chase|2024": ['opoy', 'record'],
  'Charles Rogers|2003': ['bust'],
  'Troy Williamson|2006': ['bust'],
  'Justin Blackmon|2012': ['bust'],
  'Laquon Treadwell|2018': ['bust'],
  "N'Keal Harry|2020": ['bust'],
  'Mike Ditka|1961': ['hof', 'roy', 'record'],
  'John Mackey|1966': ['hof', 'allpro'],
  'Jackie Smith|1967': ['hof'],
  'Charlie Sanders|1971': ['hof'],
  'Dave Casper|1976': ['hof', 'allpro'],
  'Kellen Winslow|1980': ['hof', 'allpro', 'record'],
  'Ozzie Newsome|1984': ['hof', 'record'],
  'Shannon Sharpe|1996': ['hof', 'allpro'],
  'Tony Gonzalez|2004': ['hof', 'allpro'],
  'Antonio Gates|2005': ['hof', 'allpro'],
  'Rob Gronkowski|2011': ['hof', 'record', 'allpro'],
  'Travis Kelce|2020': ['record', 'allpro'],
  'Brock Bowers|2024': ['roy', 'record'],

  // ---- offensive line ----
  'Danny Fortmann|1941': ['hof', 'allpro'],
  'Bulldog Turner|1947': ['hof', 'allpro'],
  'Lou Creekmur|1953': ['hof', 'allpro'],
  'Frank Gatski|1953': ['hof'],
  'Dick Stanfel|1953': ['hof', 'allpro'],
  'Mike McCormack|1954': ['hof'],
  'Stan Jones|1959': ['hof'],
  'Rosey Brown|1959': ['hof', 'allpro'],
  'Jim Ringo|1961': ['hof', 'allpro'],
  'Jim Parker|1962': ['hof', 'allpro'],
  'Forrest Gregg|1962': ['hof', 'allpro'],
  'Ron Mix|1963': ['hof', 'allpro'],
  'Billy Shaw|1965': ['hof', 'allpro'],
  'Jim Tyrer|1966': ['allpro'],
  'Jim Otto|1967': ['hof', 'allpro'],
  'Gene Hickerson|1968': ['hof', 'allpro'],
  'Bob Brown|1969': ['hof', 'allpro'],
  'Mick Tingelhoff|1969': ['hof', 'allpro'],
  'Ron Yary|1971': ['hof', 'allpro'],
  'Rayfield Wright|1972': ['hof'],
  'Tom Mack|1973': ['hof'],
  'Larry Little|1973': ['hof', 'allpro'],
  'Art Shell|1974': ['hof'],
  'Gene Upshaw|1974': ['hof', 'allpro'],
  'Joe DeLamielleure|1975': ['hof', 'allpro'],
  'Jim Langer|1975': ['hof', 'allpro'],
  'Dan Dierdorf|1976': ['hof', 'allpro'],
  'Mike Webster|1979': ['hof', 'allpro'],
  'John Hannah|1980': ['hof', 'allpro'],
  'Russ Grimm|1983': ['hof'],
  'Dwight Stephenson|1985': ['hof', 'allpro'],
  'Jim Covert|1985': ['hof', 'allpro'],
  'Anthony Muñoz|1987': ['hof', 'allpro'],
  'Mike Munchak|1988': ['hof'],
  'Jackie Slater|1989': ['hof'],
  'Bruce Matthews|1992': ['hof', 'allpro'],
  'Dermontti Dawson|1993': ['hof', 'allpro'],
  'Gary Zimmerman|1996': ['hof', 'allpro'],
  'Tony Boselli|1997': ['hof', 'allpro'],
  'Larry Allen|1998': ['hof', 'allpro'],
  'Randall McDaniel|1998': ['hof', 'allpro'],
  'Kevin Mawae|1999': ['hof', 'allpro'],
  'Orlando Pace|2001': ['hof', 'allpro'],
  'Jonathan Ogden|2003': ['hof', 'allpro'],
  'Willie Roaf|2003': ['hof', 'allpro'],
  'Will Shields|2003': ['hof'],
  'Alan Faneca|2004': ['hof', 'allpro'],
  'Walter Jones|2005': ['hof', 'allpro'],
  'Steve Hutchinson|2005': ['hof', 'allpro'],
  'Olin Kreutz|2006': ['allpro'],
  'Joe Thomas|2011': ['hof', 'allpro'],
  'Jason Peters|2011': ['allpro'],
  'Marshal Yanda|2015': ['allpro'],
  'Travis Frederick|2016': ['allpro'],
  'Tyron Smith|2016': ['allpro'],
  'Jason Kelce|2017': ['hof', 'allpro'],
  'Zack Martin|2018': ['allpro'],
  'Quenton Nelson|2019': ['allpro'],
  'Trent Williams|2021': ['allpro'],
  'Tristan Wirfs|2021': ['allpro'],
  'Lane Johnson|2022': ['allpro'],
  'Penei Sewell|2023': ['allpro'],
  'Greg Robinson|2015': ['bust'],
  'Luke Joeckel|2015': ['bust'],
  'Ereck Flowers|2016': ['bust'],
  'Cameron Erving|2016': ['bust'],

  // ---- defensive line ----
  'Bill Willis|1949': ['hof', 'allpro'],
  'Arnie Weinmeister|1952': ['hof', 'allpro'],
  'Len Ford|1954': ['hof', 'allpro'],
  'Leo Nomellini|1955': ['hof', 'allpro'],
  'Ernie Stautner|1957': ['hof'],
  'Gino Marchetti|1958': ['hof', 'allpro'],
  'Andy Robustelli|1958': ['hof', 'allpro'],
  'Art Donovan|1958': ['hof', 'allpro'],
  'Big Daddy Lipscomb|1959': ['allpro'],
  'Alex Karras|1962': ['hof', 'allpro'],
  'Roger Brown|1962': ['allpro'],
  'Henry Jordan|1962': ['hof', 'allpro'],
  'Doug Atkins|1963': ['hof', 'allpro'],
  'Tom Sestak|1964': ['allpro'],
  'Willie Davis|1965': ['hof', 'allpro'],
  'Houston Antwine|1966': ['allpro'],
  'Buck Buchanan|1967': ['hof', 'allpro'],
  'Deacon Jones|1968': ['hof', 'allpro', 'record'],
  'Merlin Olsen|1969': ['hof', 'allpro'],
  'Carl Eller|1969': ['hof', 'allpro'],
  'Rich Jackson|1969': ['allpro'],
  'Bob Lilly|1971': ['hof', 'allpro'],
  'Alan Page|1971': ['mvp', 'dpoy', 'hof'],
  'Elvin Bethea|1973': ['hof'],
  'Joe Greene|1974': ['dpoy', 'hof'],
  'Claude Humphrey|1974': ['hof', 'allpro'],
  'Curley Culp|1975': ['hof'],
  'Randy White|1978': ['hof', 'allpro'],
  'Lee Roy Selmon|1979': ['dpoy', 'hof'],
  'Jack Youngblood|1979': ['hof', 'allpro'],
  'Joe Klecko|1981': ['hof', 'allpro'],
  'Ed "Too Tall" Jones|1982': ['allpro'],
  'Dan Hampton|1984': ['hof', 'allpro'],
  'Mark Gastineau|1984': ['dpoy', 'record'],
  'Howie Long|1985': ['hof', 'allpro'],
  'Richard Dent|1985': ['hof', 'allpro'],
  'Reggie White|1987': ['dpoy', 'hof', 'allpro'],
  'Keith Millard|1989': ['dpoy', 'allpro'],
  'Chris Doleman|1989': ['hof', 'allpro'],
  'Bruce Smith|1990': ['dpoy', 'hof', 'record'],
  'Cortez Kennedy|1992': ['dpoy', 'hof'],
  'Ray Childress|1993': ['allpro'],
  'John Randle|1997': ['hof', 'allpro'],
  'Warren Sapp|1999': ['dpoy', 'hof'],
  "La'Roi Glover|2000": ['allpro', 'record'],
  'Michael Strahan|2001': ['dpoy', 'hof', 'record'],
  'Richard Seymour|2003': ['hof', 'allpro'],
  'Julius Peppers|2004': ['hof', 'allpro'],
  'Dwight Freeney|2004': ['hof', 'record'],
  'Jason Taylor|2006': ['dpoy', 'hof'],
  'Ndamukong Suh|2010': ['allpro'],
  'Haloti Ngata|2010': ['allpro'],
  'Justin Smith|2011': ['allpro'],
  'Jared Allen|2011': ['allpro', 'record'],
  'Geno Atkins|2012': ['allpro'],
  'J.J. Watt|2014': ['dpoy', 'allpro'],
  'Aaron Donald|2018': ['dpoy', 'allpro'],
  'Cameron Heyward|2019': ['allpro'],
  'Nick Bosa|2022': ['dpoy'],
  'Chris Jones|2022': ['allpro'],
  'Myles Garrett|2023': ['dpoy'],
  'Vernon Gholston|2009': ['bust'],
  'Bjoern Werner|2014': ['bust'],
  'Dion Jordan|2014': ['bust'],

  // ---- linebackers ----
  'George Connor|1952': ['hof', 'allpro'],
  'Chuck Bednarik|1953': ['hof', 'allpro'],
  'Bill George|1956': ['hof', 'allpro'],
  'Joe Schmidt|1957': ['hof', 'allpro'],
  'Les Richter|1958': ['hof', 'allpro'],
  'Sam Huff|1959': ['hof', 'allpro'],
  'Ray Nitschke|1962': ['hof', 'allpro'],
  'Maxie Baughan|1965': ['allpro'],
  'Dave Robinson|1966': ['hof'],
  'Tommy Nobis|1967': ['roy', 'allpro'],
  'Bobby Bell|1969': ['hof', 'allpro'],
  'Dick Butkus|1969': ['hof', 'allpro'],
  'Willie Lanier|1971': ['hof', 'allpro'],
  'Dave Wilcox|1971': ['hof', 'allpro'],
  'Chris Hanburger|1972': ['hof', 'allpro'],
  'Nick Buoniconti|1973': ['hof', 'allpro'],
  'Jack Ham|1975': ['hof', 'allpro'],
  'Jack Lambert|1976': ['dpoy', 'hof'],
  'Robert Brazile|1978': ['hof', 'allpro'],
  'Randy Gradishar|1978': ['dpoy', 'hof'],
  'Ted Hendricks|1980': ['hof', 'allpro'],
  'Harry Carson|1984': ['hof', 'allpro'],
  'Mike Singletary|1985': ['dpoy', 'hof'],
  'Andre Tippett|1985': ['hof', 'allpro'],
  'Lawrence Taylor|1986': ['mvp', 'dpoy', 'hof'],
  'Rickey Jackson|1986': ['hof', 'allpro'],
  'Cornelius Bennett|1988': ['allpro'],
  'Derrick Thomas|1990': ['hof', 'record'],
  'Sam Mills|1992': ['hof', 'allpro'],
  'Junior Seau|1994': ['hof', 'allpro'],
  'Kevin Greene|1994': ['hof', 'allpro'],
  'Bryce Paup|1995': ['dpoy', 'allpro'],
  'Ray Lewis|2000': ['dpoy', 'hof'],
  'Derrick Brooks|2002': ['dpoy', 'hof'],
  'Zach Thomas|2002': ['hof', 'allpro'],
  'Brian Urlacher|2005': ['dpoy', 'hof'],
  'DeMarcus Ware|2008': ['hof', 'allpro'],
  'James Harrison|2008': ['dpoy', 'allpro'],
  'Patrick Willis|2011': ['hof', 'allpro'],
  'Terrell Suggs|2011': ['dpoy'],
  'Luke Kuechly|2014': ['hof', 'allpro'],
  'Von Miller|2015': ['hof', 'allpro'],
  'Bobby Wagner|2016': ['allpro'],
  'Khalil Mack|2018': ['allpro'],
  'Shaquille Leonard|2018': ['roy', 'allpro'],
  'T.J. Watt|2021': ['dpoy', 'record'],
  'Micah Parsons|2022': ['allpro'],
  'Fred Warner|2023': ['allpro'],
  'Roquan Smith|2023': ['allpro'],
  'Aaron Curry|2010': ['bust'],
  'Barkevious Mingo|2014': ['bust'],
  'Rolando McClain|2011': ['bust'],

  // ---- defensive backs ----
  'Dick "Night Train" Lane|1952': ['hof', 'record', 'allpro'],
  'Jack Christiansen|1953': ['hof', 'allpro'],
  'Emlen Tunnell|1952': ['hof', 'allpro'],
  'Jack Butler|1957': ['hof', 'allpro'],
  'Bobby Dillon|1957': ['hof', 'allpro'],
  'Dick LeBeau|1965': ['hof'],
  'Herb Adderley|1965': ['hof', 'allpro'],
  'Bobby Boyd|1965': ['allpro'],
  'Larry Wilson|1966': ['hof', 'allpro'],
  'Willie Wood|1966': ['hof', 'allpro'],
  'Johnny Robinson|1966': ['hof', 'allpro'],
  'Lem Barney|1967': ['hof', 'roy'],
  'Willie Brown|1967': ['hof', 'allpro'],
  'Jimmy Johnson|1969': ['hof', 'allpro'],
  'Mel Renfro|1969': ['hof', 'allpro'],
  'Emmitt Thomas|1969': ['hof', 'allpro'],
  'Ken Houston|1971': ['hof', 'allpro'],
  'Bill Bradley|1972': ['allpro', 'record'],
  'Dick Anderson|1973': ['dpoy', 'allpro'],
  'Paul Krause|1975': ['hof', 'record'],
  'Mel Blount|1975': ['dpoy', 'hof'],
  'Roger Wehrli|1975': ['hof', 'allpro'],
  'Cliff Harris|1976': ['hof', 'allpro'],
  'Donnie Shell|1979': ['hof', 'allpro'],
  'Louis Wright|1979': ['allpro'],
  'Lester Hayes|1980': ['dpoy', 'record'],
  'Nolan Cromwell|1980': ['allpro'],
  'Everson Walls|1981': ['allpro', 'record'],
  'Mike Haynes|1984': ['hof', 'allpro'],
  'Kenny Easley|1984': ['dpoy', 'hof'],
  'Ronnie Lott|1986': ['hof', 'allpro', 'record'],
  'Joey Browner|1988': ['allpro'],
  'Albert Lewis|1989': ['allpro'],
  'Eric Allen|1989': ['allpro'],
  'Mark Carrier|1990': ['roy', 'allpro', 'record'],
  'Steve Atwater|1991': ['hof', 'allpro'],
  'Darrell Green|1991': ['hof', 'allpro'],
  'Rod Woodson|1993': ['dpoy', 'hof'],
  'Deion Sanders|1994': ['dpoy', 'hof'],
  'LeRoy Butler|1996': ['hof', 'allpro'],
  'Darren Woodson|1996': ['allpro'],
  'Carnell Lake|1997': ['allpro'],
  'Rodney Harrison|1998': ['allpro'],
  'Aeneas Williams|1999': ['hof', 'allpro'],
  'John Lynch|1999': ['hof', 'allpro'],
  'Ronde Barber|2001': ['hof', 'allpro'],
  'Ty Law|2003': ['hof', 'allpro'],
  'Ed Reed|2004': ['dpoy', 'hof', 'record'],
  'Lito Sheppard|2004': ['allpro'],
  'Champ Bailey|2006': ['hof', 'allpro'],
  'Brian Dawkins|2006': ['hof', 'allpro'],
  'Bob Sanders|2007': ['dpoy'],
  'Troy Polamalu|2008': ['hof', 'allpro'],
  'Nnamdi Asomugha|2008': ['allpro'],
  'Darrelle Revis|2009': ['hof', 'allpro'],
  'Charles Woodson|2009': ['dpoy', 'hof'],
  'Earl Thomas|2013': ['hof', 'allpro'],
  'Richard Sherman|2013': ['allpro'],
  'Patrick Peterson|2013': ['allpro'],
  'Malcolm Butler|2016': ['allpro'],
  'Eric Berry|2016': ['allpro'],
  'Harrison Smith|2017': ['allpro'],
  'Glover Quin|2017': ['allpro'],
  'Stephon Gilmore|2019': ['dpoy', 'allpro'],
  'Minkah Fitzpatrick|2019': ['allpro'],
  'Jalen Ramsey|2017': ['allpro'],
  'Sauce Gardner|2022': ['allpro'],
  'Kyle Hamilton|2023': ['allpro'],
  'Antoine Winfield Jr.|2023': ['allpro'],
  'Patrick Surtain II|2024': ['dpoy', 'allpro'],
  'Kerby Joseph|2024': ['allpro', 'record'],
  'Trent McDuffie|2024': ['allpro'],
  'Justin Gilbert|2015': ['bust'],
  'Dee Milliner|2014': ['bust'],
  'Trumaine Johnson|2018': ['bust'],

  // ---- specialists ----
  'Lou Groza|1953': ['hof', 'allpro'],
  'Gino Cappelletti|1964': ['allpro'],  // AFL MVP as a kicker and flanker; K weights only see the kicking
  'Jan Stenerud|1970': ['hof', 'allpro'],
  'Chester Marcol|1972': ['roy', 'allpro'],
  'Mark Moseley|1982': ['mvp'],
  'Kevin Butler|1985': ['record'],
  'Morten Andersen|1995': ['hof', 'allpro'],
  'Gary Anderson|1998': ['allpro', 'record'],
  'Adam Vinatieri|2004': ['hof', 'allpro'],
  'Justin Tucker|2016': ['allpro', 'record'],
  'Brandon Aubrey|2024': ['allpro', 'record'],
  'Roberto Aguayo|2016': ['bust'],
  'Yale Lary|1963': ['hof', 'allpro'],
  'Ray Guy|1976': ['hof', 'allpro'],
  'Reggie Roby|1984': ['allpro'],
  'Sean Landeta|1986': ['allpro'],
  'Shane Lechler|2009': ['hof', 'allpro'],
  'Johnny Hekker|2016': ['allpro', 'record'],
};

export function auditLegacy(players = PLAYERS) {
  const byKey = new Map(players.map((p) => [`${p.name}|${p.season}`, p]));
  const found = [];
  const missing = [];
  for (const [key, tiers] of Object.entries(LEGACY)) {
    const p = byKey.get(key);
    if (!p) { missing.push(key); continue; }
    const ovr = overall(p);
    const floor = Math.max(...tiers.map((t) => TIERS[t].floor ?? -Infinity));
    const cap = Math.min(...tiers.map((t) => TIERS[t].ceiling ?? Infinity));
    // What the player could reach if the attribute he is best at were perfect.
    // When even that falls short of the floor, the weight vector is the binding
    // constraint and the rating is not the thing to argue with.
    const attrs = POSITIONS[p.pos].attrs;
    const best = attrs.reduce((a, b) => (p.r[a] >= p.r[b] ? a : b));
    const ceiling = rawOverall(p.pos, { ...p.r, [best]: 99 });
    const short = Number.isFinite(floor) ? floor - ovr : 0;
    const over = Number.isFinite(cap) ? ovr - cap : 0;
    found.push({ p, ovr, tiers, floor, cap, gap: Math.max(short, over), under: short > 0, over: over > 0, best, ceiling });
  }
  return { found, missing };
}

if (process.argv[1] && process.argv[1].endsWith('legacy-check.mjs')) {
  const { found, missing } = auditLegacy();
  const bad = found.filter((f) => f.gap >= TOLERANCE).sort((a, b) => b.gap - a.gap);
  console.log(`${found.length} recorded seasons checked, ${missing.length} not in the pool`);
  if (missing.length) console.log('  not found:', missing.join(', '));
  console.log(`\n${bad.length} rating(s) off by ${TOLERANCE}+ from what the record supports:`);
  for (const f of bad) {
    const why = f.under ? `needs ${f.floor}+` : `should be ${f.cap} or under`;
    const capped = f.under && f.ceiling < f.floor ? `  (caps at ${f.ceiling} with ${f.best} 99 — the weights, not the rating)` : '';
    console.log(`  ${String(f.gap).padStart(3)}  ${f.p.pos.padEnd(3)} ${f.p.name} '${String(f.p.season).slice(2)}  ${f.ovr}  ${why}  [${f.tiers.join(' ')}]${capped}`);
  }
  if (process.argv.includes('--all')) {
    console.log('\nall clear:');
    for (const f of found.filter((x) => x.gap <= 0)) console.log(`  ${f.p.pos.padEnd(3)} ${f.p.name} '${String(f.p.season).slice(2)}  ${f.ovr}  [${f.tiers.join(' ')}]`);
  }
  process.exitCode = 0;
}
